### ISSUE TITLE
Launchpad Edits, Round II

### ISSUE THREAD

**Issue by mollybfisher** [PrimitiveSocial/madera-corporate#1]
Relatively straightforward edits from Madera regarding the Launchpad. 14 edits total, most are copy edits! :raised_hands:

https://docs.google.com/document/d/1EChE7Xyxs0UstBIkINTU9Th7H6Gfkouq-Oi_U_d0oj8/edit?usp=sharing

Here is a [link to the two images](https://drive.google.com/open?id=1E5JCkOJImEyMQl1sMZWTJDlouv_lYALm) associated with the design edits mentioned on the doc.

**Comment by regnek** [comment]
Done!
