### ISSUE TITLE
Launchpad Edits, Round III

### ISSUE THREAD

**Issue by mollybfisher** [PrimitiveSocial/madera-corporate#2]
Madera would prefer to use the Communities page as a "showcase" of certain cities/communities. 

For the purpose of this initial launch, they would like to eliminate `Lubbock` and `College Station` from the scrolling gallery. 

Then, it will be ready to launch! Just let me know when the gallery is updated and what the next steps are to get it launched.

**Comment by regnek** [comment]
Communities page updated.

For launch, I just need the correct ftp credentials and I can push the new site live.
