### ISSUE TITLE
Re-Add 'Join Our Team' Link in the Footer

### ISSUE THREAD

**Issue by mollybfisher** [PrimitiveSocial/madera-corporate#4]
Add a `Join Our Team` (career) link to the footer of the website. 
Should direct to https://www.paycomonline.net/v4/ats/web.php/jobs?clientkey=D930F158405537AD99D7C1FA70CFBC7D

(I know you've made this before, but it looks like it's disappeared!!)
![screen_shot_2019-06-12_at_11 16 09_am](https://user-images.githubusercontent.com/44073009/60044958-666a5f80-9678-11e9-8d40-6f68b6369307.png)

**Comment by regnek** [comment]
Added back in!
