### ISSUE TITLE
Convert Madera Corporate Site to Static Site Repo Template

### ISSUE THREAD

**Issue by mollybfisher** [PrimitiveSocial/madera-corporate#5]
The Madera Corporate will need to be converted to our Static Site Repo Template.

(More details to come)

**Comment by mollybfisher** [comment]
@regnek – I believe @jerredhurst would be a good starting place to check in with on this!

**Comment by regnek** [comment]
New repo: https://github.com/PrimitiveSocial/madera-static

New demo: https://primitivesocial.com/ak/madera-static

I wasn't sure if this needed to be looked over before converting their live site. Let me know if/when I should do that.

**Comment by mollybfisher** [comment]
@jerredhurst Can you be my internal review on this one?

**Comment by jerredhurst** [comment]
Yup, all good :)

**Comment by mollybfisher** [comment]
Closing!

@jerredhurst Let me know if this needs follow-up issues associated with it to have the corporate site managed with Quext.
