### ISSUE TITLE
Homepage Copy Edits

### ISSUE THREAD

**Issue by mollybfisher** [PrimitiveSocial/madera-corporate#6]
Please adjust the copy on the live homepage in two quick places:

- reword the "Quext" reference (since Madera has not announced the name)
- remove the reference to e-payment systems (in hindsight, that didn't sound like a bragging point...)

Should now read:
“Continual investment in cutting-edge technologies such as in-house development of ~~Quext Property Management Software~~ **our own property management software**, IoT devices, ~~e-payment systems,~~ and Madera’s own Asmartment lifestyle amenities program, allows for constant innovation to streamline operations and better manage your investment."

**Comment by regnek** [comment]
Done!
