### ISSUE TITLE
Homepage Copy Edit

### ISSUE THREAD

**Issue by mollybfisher** [PrimitiveSocial/madera-corporate#9]
Madera requires one edit on the Corporate homepage under the "Financial Performance" heading. Where it currently says **74** property acquisitions, it **should read 78** property acquisitions.
 
https://www.maderaresidential.com/

![unnamed](https://user-images.githubusercontent.com/44073009/62182976-5f84db80-b30d-11e9-8ed7-3e01ae0ee84a.png)

**Comment by regnek** [comment]
Done!
